name: Submodule CI
on:
  push:
    branches:
    - main
jobs:
  split-submodule-v2:
    name: split submodule_v2 branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: split submodule_v2 branch
      run: |
        git subtree split -P "Assets/DHToolbox" -b submodule_v2
        git push -u origin submodule_v2

  create-submodule:
    name: split submodule branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Create submodule branch
      run: |
        git checkout v1
        git subtree split -P "Assets/DHToolbox" -b submodule
        git push -u origin submodule
