name: Submodule V1
on:
  push:
    branches:
    - v1

jobs:
  create-submodule:
    name: split submodule branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Create submodule branch
      run: |
        git checkout v1
        git subtree split -P "Assets/DHToolbox" -b submodule
        git push -u origin submodule
